export const CATEGORYS = ["Work", "Personal", "Shopping", "Fitness", "Travel", "Finance", "Health", "Education", "Entertainment", "Other"];
export const NOTES = [
    {
        id: 1,
        title: "Meeting Notes",
        descripton: "Discussed project milestones and deadlines.",
        date: "2023-08-01T10:30:00Z",
        category: "Work",
        isCompleted: false,
    },
    {
        id: 2,
        title: "Grocery List",
        descripton: "Milk, Eggs, Bread, Fruits, Vegetables.",
        category: "Shopping",
        date: "2023-08-02T15:45:00Z",
        isCompleted: true,
    },
    {
        id: 3,
        title: "Workout Plan",
        descripton: "Monday - Cardio, Tuesday - Strength Training, Wednesday - Yoga.",
        category: "Fitness",
        date: "2023-08-03T08:20:00Z",
        isCompleted: false,
    },
    {
        id: 4,
        title: "Vacation Ideas",
        descripton: "Beach destinations, mountain retreats, cultural tours.",
        category: "Travel",
        date: "2023-08-04T12:10:00Z",
        isCompleted: false,
    },
    {
        id: 5,
        title: "Budget Planning",
        descripton: "Track expenses, set savings goals, and create a monthly budget.",
        category: "Finance",
        date: "2023-08-05T09:15:00Z",
        isCompleted: false,
    },
    {
        id: 6,
        title: "Health Tips",
        descripton: "Stay hydrated, exercise regularly, and get enough sleep.",
        category: "Health",
        date: "2023-08-06T14:50:00Z",
        isCompleted: false,
    },
    {
        id: 7,
        title: "Study Schedule",
        descripton: "Allocate time for each subject and take regular breaks.",
        category: "Education",
        date: "2023-08-07T11:25:00Z",
        isCompleted: false,
    },
    {
        id: 8,
        title: "Movie Recommendations",
        descripton: "Inception, The Dark Knight, Interstellar, Parasite.",
        category: "Entertainment",
        date: "2023-08-08T16:40:00Z",
        isCompleted: false,
    },
    {
        id: 9,
        title: "Personal Reflection",
        descripton: "Reflect on personal growth and set future goals.",
        category: "Personal",
        date: "2023-08-09T13:55:00Z",
        isCompleted: false,
    },
    {
        id: 10,
        title: "Miscellaneous Notes",
        descripton: "Random thoughts, ideas, and reminders.",
        category: "Other",
        date: "2023-08-10T17:05:00Z",
        isCompleted: false,
    },

];